networks:
  mall-network:
    driver: bridge

services:
  mall-mysql:
    container_name: mall-mysql
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./docker-data/mysql/data:/var/lib/mysql
      - ./docker-data/mysql/conf.d:/etc/mysql/conf.d
      - ./docker-data/mysql/logs:/var/log/mysql
      - ./docker-data/mysql/init:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mall-network

  mall-nacos:
    container_name: mall-nacos
    image: nacos/nacos-server:v2.2.3
    environment:
      MODE: standalone
      TZ: Asia/Shanghai
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./docker-data/nacos/logs:/home/nacos/logs
      - ./docker-data/nacos/conf/application.properties:/home/nacos/conf/application.properties
      - ./docker-data/nacos/data:/home/nacos/data
    restart: always
    depends_on:
      mall-mysql:
        condition: service_healthy
    networks:
      - mall-network

  mall-redis:
    container_name: mall-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis/data:/data
      - ./docker-data/redis/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: always
    networks:
      - mall-network

  mall-sentinel:
    container_name: mall-sentinel
    image: bladex/sentinel-dashboard:1.8.6
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: >-
        -Dserver.port=8858
        -Dcsp.sentinel.dashboard.server=localhost:8858
        -Dproject.name=sentinel-dashboard
        -Dsentinel.dashboard.auth.username=sentinel
        -Dsentinel.dashboard.auth.password=sentinel
    ports:
      - "8858:8858"
    restart: always
    networks:
      - mall-network
