server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain
    min-response-size: 2048

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 关闭自动路由，用下面手写路由
      routes:
        # ========== 认证 ==========
        # 管理认证服务
        - id: mall-auth-admin
          uri: lb://mall-auth-admin
          predicates:
            - Path=/admin/auth/**

        # 管理服务
        - id: mall-modules-admin
          uri: lb://mall-modules-admin
          predicates:
            - Path=/admin/user/**,/admin/role/**,/admin/menu/**,/admin/online/**

        # 文档路由
        - id: mall-auth-admin-doc
          uri: lb://mall-auth-admin
          predicates:
            - Path=/mall-auth-admin/v3/api-docs
          filters:
            - StripPrefix=1
        - id: mall-modules-admin-doc
          uri: lb://mall-modules-admin
          predicates:
            - Path=/mall-modules-admin/v3/api-docs
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.1.10
    port: 6379
    password: 123456
    database: 0

# 应用配置
mall:
  redis:
    enabled: true
    null-value-ttl-seconds: 60
  gateway:
    white-list:
      - /admin/auth/login
      - /admin/auth/refresh
      - /admin/auth/captcha/generate
    # 文档白名单
    doc-white-list:
      - /v3/api-docs/**
      - /mall-auth-admin/v3/api-docs
      - /mall-modules-admin/v3/api-docs

    # 监控白名单
    monitor-white-list:
      - /actuator/**
      - /error
  session:
    enabled: true
    timeout-seconds: 604800
    sliding-expiration: true
    session-id-length: 32
    clients:
      admin:
        key-prefix: "mall:session:admin:"
        device-types: [ DESKTOP, PHONE ]
        same-device-kick: true
        max-per-device: 1
      member:
        key-prefix: "mall:session:member:"
        device-types: [ DESKTOP, PHONE, TABLET, MOBILE ]
        same-device-kick: true
        max-per-device: 0
  jwt:
    enabled: true
    admin:
      secret: admin-secret-key-at-least-32-bytes-long-for-hs256
      expire: 7200000
      refresh-expire: 604800000
      issuer: mall-admin
    member:
      secret: member-secret-0123456789-0123456789-32bytes
      expire: 7200000
      refresh-expire: 604800000
      issuer: mall-member

# Api文档
springdoc:
  api-docs:
    enabled: false

# 日志
logging:
  level:
    com.we.mall: debug