<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.we</groupId>
        <artifactId>mall-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>mall-monitor</artifactId>
    <packaging>jar</packaging>
    <name>Mall Monitor</name>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- ===================== Mall Common ===================== -->
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-session</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-rpc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-monitor</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we</groupId>
            <artifactId>mall-common-swagger</artifactId>
        </dependency>

        <!-- ===================== Boot & Cloud ===================== -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>

    </dependencies>

</project>