server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 9000
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain
    min-response-size: 2048

spring:
  # ==================== sentinel ====================
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.1.10:8858  # Sentinel 控制台地址
        port: 8719                    # 客户端与控制台通信端口，默认8719
        client-ip: # 客户端IP

  # ==================== Redis ====================
  redis:
    host: 192.168.1.10
    port: 6379
    password: 123456
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

# ==================== Feign ====================
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic

# ==================== Mall 配置 ====================
mall:
  # Jwt
  jwt:
    admin:
      secret: admin-secret-key-at-least-32-bytes-long-for-hs256
      expire: 7200000               # 2小时
      refresh-expire: 604800000     # 7 天
      issuer: mall-admin
  rpc:
    service-token: mall-internal-secret-2026
  # redis
  redis:
    enabled: true
    redisson:
      host: ${REDIS_HOST:192.168.1.10}
      port: ${REDIS_PORT:6379}
      password: 123456
      database: 0
      min-idle-size: 4
      pool-size: 16
  # Session
  session:
    enabled: true
    timeout-seconds: 604800
    sliding-expiration: true
    session-id-length: 32
    clients:
      admin:
        key-prefix: "mall:session:admin:"
        device-types: [ DESKTOP,PHONE ]
        same-device-kick: true
        max-per-device: 1
        allow-unknown-device: false
  # 文档
  swagger:
    enabled: true
    title: 管理认证服务 API
    description: 管理认证服务接口文档
    version: 1.0.0
    contact-name: we
    contact-email: zwx99921@163.com

# ==================== Actuator ====================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# 日志
logging:
  level:
    com.we.mall: debug